language: node_js
node_js:
  - '10'
jobs:
  include:
    - stage: lint, test and build
      name: lint
      script: npm run lint
    - name: test
      script:
        - npm test -- --ci --coverage
        - npm run coveralls
    - name: build
      script: npm run build
    - stage: commitlint
      script: npm run commitlint
      if: commit_message !~ /^build\(deps/
    - stage: deploy
      script: npm run build && npm run release
      if: branch = master
